# Generated by Django 3.2.3 on 2021-06-09 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Pet',
        ),
    ]
